{% set name = "pyobjcryst" %}
{% set version = "2.0.2" %}
{% set sha256 = "b48b1a66973dc42d8d15c5ddcf4989cb4160cab220c3a3c60664af46926092d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - scattering.patch
    - boostpythonsuffixes.patch

build:
  number: 2
  skip: True  # [win or py2k]
  script: python setup.py install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - libobjcryst 2017.1.*
    - boost
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - libobjcryst 2017.1.*
    - boost

test:
  imports:
    - pyobjcryst
    - pyobjcryst.tests

about:
  home: https://github.com/diffpy/pyobjcryst
  license: BNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python bindings to the ObjCryst++ crystallographic library.'
  doc_url: http://diffpy.github.io/pyobjcryst
  dev_url: https://github.com/diffpy/pyobjcryst

extra:
  recipe-maintainers:
    - CJ-Wright
    - pavoljuhas
