{% set name = "pyobjcryst" %}
{% set version = "2.2.3" %}
{% set sha256 = "7c2694d55c2b7994243587ca95955935f0890d06b7d232133c68429bcd1bc208" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - libobjcryst 2022.1.2
    - boost
  run:
    # NOTE libobjcryst is implicitly added by libobjcryst run_exports
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - boost

test:
  imports:
    - pyobjcryst
    - pyobjcryst.tests

about:
  home: https://github.com/diffpy/pyobjcryst
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python bindings to the ObjCryst++ crystallographic library.
  doc_url: https://pyobjcryst.readthedocs.io/
  dev_url: https://github.com/diffpy/pyobjcryst

extra:
  recipe-maintainers:
    - vincefn
    - pavoljuhas
    - st3107
    - sbillinge
