travis:
  secure:
    BINSTAR_TOKEN: WCtQTbinhmoc+9awDvkc+JcJ6l6SM3atj0hUGIpk+7o6u34ux3qLJkua15Av6TlSmh2Ojv+3dFDubrRuOp03RsTfUkeHdwNjqdkwanGRZvjBUrBpgGGig2ivYn870GbeIJ48pWeRe5/QxOlfv8ZF8qberI6UdNGtycnGmR1Sq4VDg58PuvJzTsKPw3/ll4gQA3hRx7Jj0wjgfgydPUgMtV5+tkT37q37cg1YmcALfwTOKOiLFAz8aUcrF7xdmceFnHmudPQt0XaR947Ma0kUTWOQ9fi/koIlYaIiiwQoZfR/UzNaKs9XILF2NoSAuJOYgnIaHKldxFZCCHWq7RoO30bVDdlYbhO/ezjt9IA56UdfUjExK4PGWE9+VIZFvIVx/qywUH9U94BKlaOg7hFfSam65nzEQ+cHuNbXdiF9KFi5a1bzxnNpp7Y66ds/GdRPlzXHi7ix7Y4SPzTnTXxEf0HXX2EyAZtJui8GeJ1Kht2WV5EpK0O+oqVRCt2S8p6AOI3UoBnjOFsuWtOvzJ3Ihe6ilW7c9pYbmV3ahWdVluD7UpWNDLPp2mRD0od7U/1kAJXKlM1YxWvSWgKqx+XP2MIfdyhbxr+AlVQIc72Nt+mQolHxacwhGFtakisg6i3PE1q18UIJyJx6EhLZchObNk//8/U3AcNEwGaseJmSrsI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
