travis:
  secure:
    BINSTAR_TOKEN: OtizhwpybfvMXSYEAvD5qnAiJx4VUNp64rnM7fAFlrvRQ2yhLllwpJl6Co1Xjv/dOGNGaX+A+4/G2Tnx33t3QGlD8yVBQgO6r8UefV17h7j0ZJk4gVGm+20EB14nnweUVlHY9PtrUvjXKMckACt5+V4+mXiR3H/4OhF6sfOmfx+DnK3XSPoebNtuvuNH8VCPp7mlib1LC4j2bkJlA8YiFc2zsLZ7IVGVZWsNqorJrVt8QmCliB/pMgdpRCaoxE6lOj9wL0wbBa5BhlRaSapMVED7WpBtt8AXBeVMGjHkyLBzG2rkFYmJxfiUxfC93PSQHPeWmhlivyOfGRP8AVvQmzhM0M4K3Y2mJc3N46iMyKLRQ/syuQ/rBmWXr3z9d67W7KE7o8NFcnpKuLY6tBZezRG85RiELSadwa+N/gx8/1FsBRk0HfJnFHtSqoFeHdO7aSQodhBb5AE8a6jesxJadAdbfh7MZoHVOCGORuA7aEdTHqUDHm9aGvM+zKV/+MFJ0I3p0VBgyst+FDhwpKPg7rc9W1OmMDe1bY9WFNPfxM58kouKKpB24893k+xHZywhTxktKc9xXXtqZ4qgSiwBNZMfVGb5x2c9rURksuTLPGn/ZesrfL3Jbk8dMdgCIcdhQiqgkTxE1A6X36qnnNdqrLdcfcbxlqsHLu8zfI5gDYw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
